---
layout: page
title: "Writing a personal statement for graduate school"
author: "Marianna Y. Zhang (marianna.zhang@stanford.edu)"
date: "July 2020"
output:
  html_document:
    toc: yes
---

```{r knitr-config, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
require("knitr")
```

# Preamble
This page contains **informal personal advice** for prospective PhD students **from one person's particular experience and perspective** - it is not a comprehensive guide by any measure.

This advice is primarily based on my experience applying to US-based PhD programs in developmental psychology as a fourth-year domestic US undergraduate at a large research university in fall 2018.

Academia involves an endless transmission of knowledge, and this information for prospective PhD students is no exception. I owe the knowledge documented here to so many people, including but not limited to: Sam Johnson, Yarrow Dunham, Laurie Santos, Frank Keil, Jayden Ziegler, Narges Afshordi, Susan Carey, Jesse Snedeker, Susan Goldin-Meadow, Alex Shaw, and Anne Henly. Thank you, and passing on the favor! 

# Before you start
- Are you ready to apply to graduate school?
- Do you have a set of concise and well-defined research interests/questions for graduate school?
- Do you have at least the start of a list of places to apply to? Take a look at their deadlines, personal statement requirements, whether they require other statements besides the personal statement (e.g. a diversity statement), etc. to get a sense for your timeline and application components. 

# What is the personal statement?
**Your personal statement (or statement of purpose) is typically the single most important piece of your application to graduate school.** (Caveat if you are applying to philosophy programs, it is your writing sample instead.) You can have great grades, GREs and stellar letters of recommendation but if you do not clearly convey why your intellectual interests and preparation make you an exceptional candidate for the particular program you are applying to, you will be very unlikely to get in. 

The personal statement is somewhat misleadingly named. This is a **completely different document from a college application personal statement.** It’s not a statement about your personal life, rather a statement about you as a researcher - your intellectual development to your interests today, and what you’d like to explore in grad school. It is a pitch for yourself that is simultaneously backward-looking (how you got to where you are today), in the present (where you are now, what you’re interested in now), and a projection of yourself into the future (what would you like to study, where/who would you like to work with). 

**The personal statement is a difficult piece of writing that may be unlike any other kind of writing you've done before.** It will take a lot of time to think through, a lot of time to write, a lot of time to revise, and a lot of time to tailor to each program you’re applying to.

**The earlier you start on this, the better! The summer before you apply is a great time to start working on this statement.** For example, starting to work on a statement in July for an application deadline of that same fall (November/December), for admission the following fall. 

Length restrictions vary across programs, so check what programs you’re applying to for the length requirement (may vary from 2 pages single-spaced to 500 words!), and if they require any other statements, e.g., a diversity/personal history statement. Personal statement prompts differ across programs, but are generally relatively vague - readers typically don’t read the statement with regard to the exact prompt, and are typically expecting the info below. 



# Know your audience
For each program, you'll have several readers you'll want to target: **your primary faculty of interest, probably a few other faculty in that area of the department**, and perhaps some senior graduate students. 

**Your readers are experts who know the field and the topic.** Describe your interests using the terminology and framing a scientist in the field would, to demonstrate that you know your stuff. Drop the names of people who you worked with who they might know, to help them situate you in their mental social network. And if you'd like to work with them, name them in your last paragraph! 

**Your readers are tired and frazzled, so grab their attention!** Your statement and application will be part of dozens of statements and applications they'll read that day like yours, and part of hundreds they might be reading that month. They'll be rushed, their eyes will jump over walls of text, and they'll be wondering when they can end their day. You can help them efficiently extract your pitch by using the standard structure they’ve learned to efficiently skim, clearly and succinctly explaining your interests in the intro, and using clear topic sentences. You want to knock through their stupor and shake them into enthusiasm and excitement about you. 

It’s helpful to have some idea of where/to whom you’re applying at this point. Okay if the list isn’t finalized, but it’s helpful to have at least 1-2 definitive programs/advisers in mind so you can write with them in mind. 

# Goals of the statement
Your personal statement will need to:

1. **Describe the overarching intellectual interest that is motivating your pursuit of a PhD in whatever field, and articulate a cohesive set of intellectual questions and approaches to these questions that you want to pursue in grad school.** You should have a set of interests/research questions at an optimal level of specificity such that they could guide a coherent and fruitful research program for 5-6 years (or however long your program is). Pitch these questions in ways that shows the reader why you think these are so important and interesting, to get them excited as well. 

2. **Weave a narrative of intellectual and academic experiences that have shaped your interest in these questions.** This section should also demonstrate that you have relevant experience in the topic that make you qualified to explore your particular questions with your particular approach in graduate school. This section should demonstrate that your intellectual maturity - you've encountered difficulty and failure (which are inevitable in grad school), and overcome them, and you're resilient and prepared for the challenge of independent research. 

3. **Explain why this set of faculty at this program** is particularly suited to your development and furthering your intellectual goals. Why here?

# The standard structure
The 3 primary goals are typically communicated in a standard 3-part structure described here. **This standard structure works well for most/typical candidates, and readers will likely expect/have learned to efficiently read it.** 

However, one single structure won't work best for everyone! It's important to note that standard structure is overly rigid, more rigid than necessary, especially if you're not a "typical" candidate. But as they say, **you've got to know the rules before you can break them.** You can definitely play with this structure and deviate from it, just be mindful in your choices to do so, and check that it works in feedback. 

## 1. Your intellectual interests and goals (intro paragraph)
**Start with a hook that immediately captures the reader's attention and motivates your topic.** This could be a compelling example, a rhetorical question, a personal anecdote, a really cool fact of broad interest, a mind-blowing statistic, etc. 

- Why is this topic intellectually important?
- What drew you to this topic? What's something cool and awesome about this topic?
- If you're going to have a cutesy hook, check that it doesn't come off as cliche (e.g., "Ever since I was a child, I loved..."). 
- Why is this an important topic to focus on? What theoretical or practical issues are at stake? Why is this a topic that keeps you up at night, that is scientifically interesting, that is worth studying and funding? Make clear why this is a scientifically interesting question. 
- This section will set up why you're determined to pursue a greater understanding of a particular issue.

**Describe your specific interests/research questions.** What specific scientific questions would organize your research program and pursuit of a PhD in whatever field? (e.g., I’m interested in understanding how children's social environments support their language learning, NOT I want to BE a researcher, therapist, professor, etc.)

- Introduce your broad topic/research questions, and then elaborate with some more specific questions. 
- Discuss your interests using the terminology and context of the scientific literature, so that it is clear you have a basic familiarity with current work. Posing specific interesting scientific questions gives the reader a glimpse of how you approach the topic, and gives the reader confidence that you know what you're talking about. Talk about the topic in a way that other faculty you're targeting would resonate with, that vibe with the literature in the field (this part could be mildly tailored by program). 
- *Optional:* if there is a specific theoretical framework (e.g., neural networks, Bayesian approaches), methodology (e.g. fMRI), or population (e.g., infants) that is important to how you plan to explore your interests, you can mention that here.

**By the end of this first paragraph, the reader should be able to clearly articulate in 1-2 sentences what your research interests are.** This will 100% come up at the start of discussions in admissions meetings about your application, and will be the basis on which people assess your fit with the interests of your target faculty and the program more broadly. 


## 2. Your relevant experiences and journey (body/middle paragraphs)
**Weave a narrative of your experiences (research, coursework, non-academic work and volunteer experiences, personal experiences), and how they have shaped your thinking and development as a scientist.** These paragraphs will show the arc of your development, and also demonstrate your qualifications for studying the interests you established in the intro paragraph. 

- Choose 2-3 experiences to focus on, dedicating one paragraph to each, so you can go into enough depth on each. Glancing at your CV may help here with selecting experiences.
- It’s generally best to focus on research experiences, rather than coursework or personal experiences. Graduate school is mostly about research, so research experiences will be most relevant in demonstrating relevant background and research skills. 
- You can use space as a signal of relative importance of the experiences - spend more space unpacking key relevant experiences, even if they were relatively short experiences in terms of time. 
- Play around with the order of experiences, there's no one single order that works best for everyone! For example, you could try real-life chronological order (i.e., start with earliest experience, end with most recent experience). Often transitions work naturally chronologically, because in real life, the takeaway from one experience really did lead you to the very next experience. But you could also try some other order and see how the narrative turns out that way! No one will know the ground truth, so it can be fun to play around with portraying your journey in different ways, and weave different narratives of yourself. You might discover a different order that works best for you. 

For each experience, describe:

- Summarize your takeaway ("I first learned...", "I grew interested in..."), and introduce the experience (where was it, who did you work with, for how long?). 
- What was the research question? Why was it interesting? What approach or studies did you use to answer the question? What were the results and end products?
- If a project didn’t turn out the way you had hoped, this could be an opportunity to demonstrate that your intellectual maturity - you've encountered difficulty and failure (which are inevitable in grad school), and overcome them, and you're resilient and prepared for the challenge of independent research. 
- Weave in honors, awards, conference presentations, publications, honors thesis that speak to your accomplishments. 
- Tailor level of detail on each experience by how relevant/important the experience was to your current interests. 
- Specify what your personal responsibilities and contributions were in the context of that experience, highlighting intellectual contributions (e.g., developing the study design is generally more of an intellectual contribution than collecting data). 
- Use lots of “I + specific verb” sentences here to emphasize what you did! (e.g., "I developed", "I designed", "I presented") Front yourself, and take credit for your contributions! This is often hard for those of us who don't like fronting ourselves and coming off like we're bragging. A few writing tips: Use "I" instead of “we” if it’s really something *you* primarily did. Put yourself in subject position instead of some inanimate object (e.g., "I designed..." instead of “The study I designed…”), and use active instead of passive language ("I created the study design" instead of “The study design was created by me”). 
- Discuss any specialized skills or abilities you have developed for pursuing your interests (e.g., you recruited participants from a specialized population, learned ASL, collected data using EEG, developed a coding scheme, learned fMRI analysis, learned R). Describe how you used these skills, and how they contributed to the project and to your own thinking about the research.
- End with what you learned, your takeaway from that experience. How did this experience push you forward to the next experience (good transition to next paragraph), or towards your current interests (good tie-back to the intro)? 

## 3. Why here? Why this program/these faculty? (last paragraph)
This paragraph will be **heavily tailored by program.**

**Describe why your interests drew you to this program, department, or institution.** What kind of graduate environment are you looking for? How does this program or department fit with your ideal environment? Is there a rich environment of people working on this broad topic who you'd benefit from?

**Name and pitch yourself to potential advisers (1-2, max 3) who you'd like to work with.** Focus on describing the intersection between your interests (reader should have a good sense of your interests by now from the first paragraph, but you can remind them in brief) and their interests (describing their interests in a way that clearly demonstrates you know what they’re doing). 

- Name the faculty in the order you'd prefer to work with them. Generally, you can name your primary adviser(s) of interest first, and if you'd like to be co-advised, explicitly mention that. Let the length of your description for each faculty for each be a signal as well, ranging from a sentence to 2-4 sentences per faculty (more length for primary adviser). 
- Why would you vibe with each of them? Are you particularly keen on working with one faculty advisor, and if so, why this particular person? If you are leaning more toward a cluster of advisors, as well as the department more generally, why? Do some research, get to know what their current research programs are beyond just superficial website details.
- For each person you name, explain how your interests intersect with theirs, why they might contribute to your development as a scientist. explain what YOU bring to their research, how your interests will contribute in interesting ways to the lab. 
- A helpful sentence structure here that reminds the reader of your interests, and demonstrates you know the faculty member’s while keeping the focus on the intersection: “Given my interests in A and X’s interests in B, I would be excited to work with X in exploring [specific intersection]”
- Really try to reach out and excite the reader here: the reader is probably one of the people you listed! Faculty are thrilled by students who have read some of their work, have thought critically about it and other literature, and raise some interesting further questions or ideas to explore. And, it helps with admissions to have multiple faculty championing your case. 

- Keep this paragraph focused on academic and intellectual reasons why this faculty/program/institution would be a great fit. Avoid focusing on non-academic reasons why you would love to go to this place, even if they are true: e.g., I’ve always wanted to live in this location, it’s close to home, the university has great extracurriculars, etc. 

Some possible ways to close (many possible!):

- Wrap up this “why here” paragraph. "Overall, X program is amazing and I’d be excited to..."
- Your future career goals and aspirations beyond graduate school. What do you need a PhD for? The most typical answer is that you need a PhD to be a professor who researches X. 
- Circle back to the hook for a poetic ending.
- It's not necessary to end with “thank you for considering my application!” 


# Notes on content
- If you have a personal experience or background (e.g., your experience as a member of a particular social group, your experience growing up in a certain country, your experience as someone who is bilingual, etc) that has motivated your academic interest in a topic, it’s okay to mention that! Could be a great hook, or compelling justification for why you find the topic interesting and important. But be careful not to focus too much on personal experience - consider the purpose of each paragraph, make sure the paragraphs are still centered on your academic interests, your research experiences, etc. 
- A personal statement can also be a space to explain a break from schooling, a gap in your transcript, etc, framing it again as a growth/overcoming adversity experience. I’m not sure how this actually looks or how to do it, but this is definitely a thing you can do! Alternatively, another space to address this in your application is to ask a rec letter writer to cover this in their rec letter.
- It's generally not advised to mention mental health challenges you’ve faced. This is extremely abelist and deceptive, I know. I've heard unfortunately it’s possible some faculty might consider such experiences as indicative of mental instability that might threaten your potential to succeed in grad school. Definitely get feedback on this during the feedback process if you have questions or concerns here. 

# Writing mechanics
- **Craft your intro paragraph and topic sentences.** Read through the intro paragraph, and **only** the first/topic sentences of following paragraphs. Is that a good summary of your pitch? Spend a lot of time crafting those topic sentences so they communicate the topic/point of their paragraphs. 
- **Check for transitions between paragraphs and ideas.** You probably wrote things in chunks, so it’s great to go back and add in connectors and transitions. 
- **Try to use verbs over nouns (to the extent possible).** Verbs are exciting and communicate action! Verbs that are turned into nouns through nominalization tend to become heavy, dense, and abstract. Psychologists unfortunately love to nominalize things to make them Serious Psychology Concepts Worthy of Study, but since you do also want to use the language of field to show that you’ve read the literature and can talk like a scientist, you may need to keep some nouns in there. 
- Use your prime real estate wisely.
-- In English, we read left to right, top to bottom. Our attention is drawn to white spaces, and bold/underlined text, and we glaze over walls of (especially single-spaced) text. All this is to say your reader will be drawn more to the first (and last) sentences of each paragraph over the middle, and more to the start of a document than the middle of a document. Make sure you put important info there. 
-- In addition, we typically start our sentences by delivering old information, and ending with new information (observe the way we talk). Within a sentence, you should put new information or information you want to emphasize last. 
- Unlike in most academic writing, you should definitely be using first-person in this statement. This statement is all about you (as a researcher)! Don’t hesitate to center yourself and promote yourself, especially in the experiences body paragraphs, by starting sentences with “I” in subject position.

# Formatting
- Times New Roman 12 point font, single spaced is typical. Not necessary to get fancy with font, think of this as a CV.
- Unlike an academic paper, people generally don’t include references. Extraordinary exceptions: it’s *the* central paper for the kind of approach/topic you’d like to study, or it’s your own publication you want to show off in one of the experiences body paragraphs. 
- If you’d like, totally optional, you can bold/underline sentences you really want the reader to notice. These might be your interests sentences, for example. Be careful with bolding/underlining - selective use can be powerful, but overuse can overwhelm the reader, diffuse attention across too many things, and overbolding cut down on your space. Italics, somewhat confusingly, tend to visually recede and demote the visual salience of text, so don’t use it for emphasis (e.g., this looks more prominent than *this*). 
- If you’d like, you can include your name in the top margin of each page, in case any old faculty print out your statement and need to remember whose statement this is. 

# The writing process
Here's the writing process that was helpful to me. Do adjust to your needs, your writing style, and your timeline!

## Plan and brainstorm.
- **Set a timeline.** How much time do you have? Set specific actionable time-bound goals for yourself to scaffold your way up, eg I will find at least 1 writing buddy by next Monday, I will pick out my 2-3 experiences by date, I will have the intro written by date. 
- **Find writing buddies.** Is there anyone else going through the same process who you can write with or hold yourself accountable with? Form a writing/peer review group and set group writing time and deadlines! 
- **Start with self-reflection.** Reflect on what your interests are, why you’re interested in them, and what led you to these interests. 
-- If you have a CV handy, you can jog your memory by looking at experiences listed on your CV, and mentally reminding yourself of your trajectory.
-- What experiences were critical and super important in guiding you to your current interests? Can you identify 2-3 such experiences? 
- **Create a doc, put in the template structure, and jot down freeform notes.**
-- Create a new doc. Immediately relieve yourself of the terror of a blank page by pasting in the standard structure section template (eg intro, experience 1, …)
-- Jot down some freeform notes on the questions listed under each section in this doc. Don’t worry if it’s not a complete sentence or just a half-baked thought, the important thing is to get key phrases and ideas on the page. 
-- For the last paragraph (why here), focus on the program you’d love most (should be easiest to write about), or the program with the longest personal statement length cap (it’ll be easier to tailor shorter). 
- **Organize your notes into an outline.** Organize your notes within each section into an order that makes sense. Again, you can revise and play with order later. 

## Write the first draft.
- **Start by writing the most important sentences (topic sentences, interests).**
-- Make sure the last sentence(s) of the first paragraph declaring your interests are super clear and compelling. Imagine a professor in this field asking you, “So what are you interested in?” and try answering that in 1-3 sentences out loud. Write down what you said and craft from there. 
-- First paragraph and topic sentences are critical. Spend a lot of time on them - readers’ eyes are naturally drawn to to the first sentences of paragraphs, so it’s your most valuable real estate. Make sure you spend it effectively. These should be concise, clear statements that declare the topic/point of the upcoming paragraph that need no previous context (avoid demonstratives that refer back, eg that experience…). 
- **Write frequently and regularly, bit by bit.** Writing is hard, especially if you have full-time classwork and/or a job going on. Try to write a tiny bit every day. It doesn’t need to be Shakespeare, just try to get words on the page. Don’t worry about length right now. Hold yourself to your deadlines and commiserate with your writing buddy. 
- **Make peace with the fact that your first draft will be terrible, and rejoice in the fact that your future drafts will be even better.** 

## Revise, revise, revise with feedback from others. 
**Look over your draft, sleep on it, and edit your writing.** Your first critic will be yourself! Some tips for self-revision:

- Sleep on your writing and look at it later with fresh eyes. 
- Read your statement out loud to yourself (or use the Review > "Read Aloud" feature in Microsoft Word), so your ears can freshly catch what your eyes have grown used to. You might catch jumps in the narrative flow, or clunky sentences. Notice if you spontaneously correct or change anything on the fly, and consider changing the writing to match! 

**Get feedback from literally everyone you can get a hold of who knows something about your field** who isn't someone you're applying to work with:

- Your research mentors / rec letter writers
- Graduate students you know or find on academic Twitter
- TAs/professors of classes you've taken
- Your department’s undergraduate liaison
- Your institution’s career development office
- Your institution’s writing center
- People you know who are also writing personal statements and applying to graduate school. (And review theirs - peer feedback!)
- Roommates, significant other, family?? Even someone who doesn't know about your field can be helpful in pointing out when you slide from accessible to technical terminology, the writing mechanics, etc.  

Make sure to thank these people and update them later on your application outcomes!

Keeping track of comments and suggestions:

- If you're using Microsoft Word, you can ask people to go to Review > "Track Changes", so changes people make will be mark-ups to the document rather than direct edits, and you can choose to either accept or decline changes. People can also insert comments by using the Review > "Comment" feature.
- If you're using Google Docs, you can ask people to use the "Suggestions" feature (click the little pencil icon at top right), so changes people make will pop up as suggestions rather than direct edits. People can also insert comments by using the "Comment" feature.

**Revise, revise, and revise. Go through as many rounds of feedback as you can.**

## Tailor your statement to each program.
Great now you have an amazing statement! We’ll now need to tailor this main statement into multiple program-specific statements. 

I recommend copying this file to create a new file for each additional program. Start by tailoring your statement to programs that you are passionate about, or programs with the next longest word limit. If you have programs with widely varying length caps, move down the list in order of word length, so that you gradually tailor shorter and shorter instead of needing to rewrite or read things. 

**Warning: tailoring always takes longer than you think, and multiply by the number of programs you’re applying to.**

- Do your research!! Cannot emphasize this enough. Make sure to give specifics about faculty interests in the last paragraph go beyond a regurgitation of info on faculty's public website. 
- Spend a lot of time and gets lots of feedback for the top few statements for programs you really want to go to! 


**Much of the tailoring will be in the last “why here” paragraph - that paragraph may need to be completely overhauled by program.**
- Really make sure you’re getting into specifics of the program. 

**Another warning: don't overtailor!** Be truthful to yourself and your interests, and represent yourself fairly. Don’t claim you’re interested in something you’re not, or claim an approach/framework you don’t believe in, just to grab someone’s interest.

- An honest representation will help the reader assess whether or not you - your true self - would be a good fit at the program. Being honest means that acceptance will be a more honest signal of fit. 
- If you honestly represent your interests, and a reader thinks they’re awesome but don’t quite fit with any faculty, a rejection will be better for both of you and save both of you time. 
- If you present yourself as interested in something you're not, which convinces someone to accept you, you may not know whether you actually do truly have a good fit there for 5-6 years. 


**Tips for cutting down on length:**

- Cut anything that the reader can probably infer, which you don’t need to say explicitly. 
- Cut adjectives and adverbs from sentences. Consider whether the meaning of the sentence comes across fine without them, and whether they’re really worth the real estate. 
- Consider whether you need to go into the amount of detail you do on each experience. 
- Compress ideas that may not deserve their own sentences into dependent clauses, emphasizing the important point for the reader to take away. (“Unfortunately the results were not what we predicted, blah blah. However, I did learn…” → “Although the results were not what we predicted, I did learn…”)

## Submit your personal statement!
**Have a finalized version of your statements ready at least a few days before each deadline.** Sleep on it, feel good about it, and even submit it a day or two early! Congrats you're done!!

## After graduate school admissions
**Save a copy of your personal statements for each program.** This document is a snapshot in time, a time capsule of what you were interested in at this moment in time, and what you projected your future to be. This document will be great to reference later on even as you enter graduate school, as a reminder of what you were interested in studying, why, and what collaborations you wanted to do. 

A personal statement will provide raw material for future statements, such as fellowship statements (e.g. [NSF GRFP](https://www.nsfgrfp.org/) research statement and personal statement).